#!/bin/bash
url="${1}"

supportedTypes=('redd.it')

DATE=`date +%Y-%m-%d_%H-%M-%S`

# Store client identity number to direct data.
id=$(kdeconnect-cli -a --id-only)

# check if user exists.
if [ -z "$id" ]
then
    echo "No user connected"
    exit 1
fi


path="/tmp/KDEConnEx/"
name="kdeconn-$DATE"
$(mkdir -p $path)
fileType=$(echo $(basename $url) | sed "s/?.*//g;s/^.*\.//")


# resource identifier
kind=$( echo $url | grep ${supportedTypes[0]} )

function redditGif(){
    if [ "$fileType" = "gif" ]; then
        fileType="mp4"
    fi
}

# save file
# function saveFile(){
#     #
# }

if [ ! -z "$kind" ]; then
    redditGif
fi

# arguments (Device-ID, target URL)
function downloadContent(){
    file="$path$name.$fileType"
    $( wget -qO $file - "https://external-preview.redd.it/ESt8FJHjA1Czi-QvKojxPD6K3-G7zKafvr9fWp6noKg.gif?format=mp4&s=1d8847dfc8d0e0329fbdb981672972ba888334d9" )
}

# transfer to connected device
function sendFile(){
    # echo "Sending...."
    $(kdeconnect-cli -d $id --share $file)
}

function start(){
    downloadContent
    sendFile
}

start

#wait $(rm -rf $filename)

